import {
  Home,
  MessageSquare,
  Briefcase,
  Activity,
  Cpu,
  FlaskConical,
  Plane,
  Utensils,
  Trophy,
  Palette,
  Music,
  GraduationCap,
  Leaf,
  Scale,
  Shirt,
  Coins,
  History,
  BookOpen,
  FileText,
  Film,
  type LucideIcon,
} from "lucide-react";

export const DOMAIN_ICONS: Record<string, LucideIcon> = {
  LIFE: Home,
  COMMUNICATION: MessageSquare,
  BUSINESS: Briefcase,
  MEDICINE: Activity,
  TECHNOLOGY: Cpu,
  SCIENCE: FlaskConical,
  TRAVEL: Plane,
  FOOD: Utensils,
  SPORTS: Trophy,
  ART: Palette,
  MUSIC: Music,
  EDUCATION: GraduationCap,
  ENVIRONMENT: Leaf,
  POLITICS: Scale,
  FASHION: Shirt,
  FINANCE: Coins,
  HISTORY: History,
  LITERATURE: BookOpen,
  LAW: FileText,
  ENTERTAINMENT: Film,
};
